### PR TITLE
add OWNERs file

### LINKED ISSUE #1054: Missing OWNERS file for our product registry
## Which area/kind this issue is related to?

 /area registry

## Issue Description

The OWNERS file is missing for the stacks in our product registry.  We should update with the proper owner and also update the contributing guide to to reflect this step

Target Date:

March 22, 2023

### PR DESCRIPTION
**Pull request by kim-tsao**
Fixes: https://github.com/devfile/api/issues/1054

### CODE REVIEW

**Review by michael-valdron — COMMENTED** [review]
> User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

Are we making an exception for the stack owner in this case? Or should we add them as a collaborator first?

**Comment by kim-tsao** [comment]
> > User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
> 
> Are we making an exception for the stack owner in this case? Or should we add them as a collaborator first?

good question.  I don't know how this is handled.  @johnmcollier do we usually add the stack owner to this repo if they are new?

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Comment by kim-tsao** [comment]
@ehsavoie, FYI we have added your name to the OWNERS file for these two stacks

**Pull request merged**
